apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJiWEowZUdWbE9tZHBkR2gxWWw5d1lYUmZNVEZCUVVWTlZrcFJNRmwwZUd4dFJHSklVbE5YY0Y5YVEwbFlRemhwVXpKMWJXMXJWVVY2Vmt4QmFrUjZWMk5STTI5a05YcFpNVWhRVGpCUWNHUnFSM0JOVERSR1FsSkdWMU5vYVV3emFURkVVUT09IgoJCX0KCX0sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKCSJjdXJyZW50Q29udGV4dCI6ICJkZWZhdWx0IiwKCSJwbHVnaW5zIjogewoJCSIteC1jbGktaGludHMiOiB7CgkJCSJlbmFibGVkIjogInRydWUiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
